<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>pipe on Utop's Blog</title><link>https://www.ffutop.com/tags/pipe/</link><description>Recent content in pipe on Utop's Blog</description><generator>Hugo -- gohugo.io</generator><language>zh-cmn-Hans-CN</language><lastBuildDate>Mon, 20 May 2019 00:00:00 +0000</lastBuildDate><atom:link href="https://www.ffutop.com/tags/pipe/index.xml" rel="self" type="application/rss+xml"/><item><title>pipe 导致的 CLOSE_WAIT</title><link>https://www.ffutop.com/posts/2019-05-20-close_wait_problem/</link><pubDate>Mon, 20 May 2019 00:00:00 +0000</pubDate><guid>https://www.ffutop.com/posts/2019-05-20-close_wait_problem/</guid><description>&lt;p>历时一周总算把导致服务大量 &lt;code>CLOSE_WAIT&lt;/code> 的原因给找到了。打印任务调用栈果然的必备手段啊！&lt;/p>
&lt;h2 id="问题描述">问题描述&lt;/h2>
&lt;p>Python 服务 A，用于接收心跳包确认其他服务是否存活。其他服务每 5 分钟向 A 发送一次心跳包；总计 &amp;lt; 100 个其他服务。&lt;/p>
&lt;ul>
&lt;li>05-11 19:30 ，首次出现 Python 服务大量 &lt;code>CLOSE_WAIT&lt;/code>，至 13 日发现，总计 10k 左右 &lt;code>CLOSE_WAIT&lt;/code> 的 TCP 连接。05-13 15:30 通过运维平台重新部署&amp;hellip;&lt;/li>
&lt;li>05-14 16:30 ，再次出现。19:30 手动重启。&lt;/li>
&lt;li>其间给 Python 服务 A 添加了打印调用栈的模块 &lt;a href="https://pypi.org/project/pdbx/">pdbx&lt;/a>，通过运维平台重新部署&lt;/li>
&lt;li>05-17 19:00 ，再次出现。等待打印调用栈，不小心杀掉了服务&amp;hellip;&lt;/li>
&lt;li>05-19 14:30 ，重现。&lt;/li>
&lt;li>05-20 08:30 ，查找原因，解决问题。&lt;/li>
&lt;/ul>
&lt;p>由于不是本人负责的服务，于 16 日凭兴趣开始有限介入，协助排查。现将排查流程一一记述，给自己和大家未来排查问题提供一个借鉴。&lt;/p></description></item></channel></rss>